[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "borealis"
version = "0.6.1"
description = "SuperDARN Digital Radar System"
readme = "README.md"
authors = [{name = "SuperDARN Canada"}]
license = {file = "LICENSE"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "posix_ipc",
    "zmq",
    "pydarnio",
    "backscatter",
    "protobuf",
    "scipy",
    "h5py",
    "structlog",
    "graypy",
    "rich",
    "pydantic<2",
]

[project.optional-dependencies]
gpu = ["cupy"]
dev = [
    "black ~= 24.0",
    "pre-commit",
    "jupyter"
]

[project.urls]
Homepage = "https://borealis.readthedocs.io"

[project.scripts]
steamed_hams = "scripts.steamed_hams:main"
restart_borealis = "scripts.restart_borealis:main"

[tool.setuptools.packages.find]
where = ["src", "build"]
exclude = ["usrp_drivers", "src.borealis_experiments.testing_archive*"]
