01:00    05:01    Common Time (1-min) (no switching)


05:01    06:08    Special Time (ARASE) (see Note G)
06:08    07:03    Discretionary Time
07:03    18:12    Special Time (interleavescan) [ALL] (see Note A)
18:12    20:10    Common Time (1-min)
20:10    21:00    Special Time (interleavesound) [ALL] (see Note B) [  HKW  HOK  ADW  ADE  KSR  KOD  CVW  CVE  FHW  FHE  BKS  WAL  PGR  SAS  ]  {interleaved  normalscan}
# This line and the following should be skipped
#21:00    21:06    Common Time (1-min) (normalsound) (see Note C)
21:00    21:06    Common Time (1-min) (normalsound) (see Note C)

# The following line should be skipped since it's all whitespace
    # this should also be a comment and skipped
21:06    21:07    Special Time (normalsound) [ALL] (see Note D)
21:07    21:08    Special Time (THEMIS) [ALL] (see Note E)
21:08    27:00    Special Time (RBSP) [ALL] (see Note F)
27:00    27:02    Special Time (ST-APOG) (see Note H)
27:02    28:08    Special Time (PFISR) (see Note I)
28:08    31:24    Common Time (1-min) (no switching)

# Total Common Time (1-min):  Basic.
# Total Discretionary Time:  Some amount of hours anyways
# Total Special Time:  who knows?

# Notes:
anything that goes here should be ignored completely



01:00   05:00   Discretionary Time

Note B: Test.

Another note

023578-0q972346

Blah blah blah


Note A: This is a spacecraft working group request to support the ARASE/ERG
mission. All radars should run interleaved_normalscan (a full scan of at
least 16 beams with a non-sequential manner that interleaves the beam number,
with a scan time of 1-min).
