#!/bin/sh
#
# This shell script if placed in /etc/apcupsd will be called by /etc/apcupsd/apccontrol when the
# UPS goes back on to the mains after a power failure.
#
# Must be run as root


# Send signal to start Borealis, or check if the stop_radar.sh process was called by onbattery and
# cancel it
HOME="/home/radar"
SCRIPT_DIR="${HOME}/borealis/scripts"
PID_FILE="${HOME}/borealis/stop_radar.pid"
FLAG_FILE="${HOME}/borealis/apcusd.flag"

# First, check if this computer was running Borealis. If it was, then onbattery should have created
# a flag file, letting this script know it needs to turn the restart_borealis service back on
NOW=$(date +'%Y-%m-%d %H:%M:%S %z ')
if [[ -f $FLAG_FILE ]]; then
        PID=$(cat $PID_FILE)
        if kill -0 "$PID" >/dev/null 2>&1; then
                # stop_radar.sh hasn't executed yet - cancel it
                echo "$NOW Cancelling the scheduled stop_radar.sh (PID $PID) command"
                pkill -9 -P "$PID"
        fi

        # The restart_borealis service will start the radar if it isn't already running and handle
        # any further restarts.
        systemctl restart restart_borealis.service

        # Clean up temporary files
        rm $PID_FILE
        rm $FLAG_FILE
fi

exit 0
