#Copyright 2016 SuperDARN

"""Scons sconscript file to generate utilities library"""
import os

Import('*')

# add source directories (at all levels) to the include path
# and add their contents are build targets
matches = []
for root, dirnames, filenames in os.walk(os.getcwd()):
    for dirname in dirnames:
        globStr = "%s/*.c*" % dirname
        matches.append(Glob(globStr))

Lib('utils', matches)