# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sigprocpacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sigprocpacket.proto',
  package='sigprocpacket',
  syntax='proto3',
  serialized_pb=_b('\n\x13sigprocpacket.proto\x12\rsigprocpacket\"\x84\x03\n\rSigProcPacket\x12\x36\n\trxchannel\x18\x01 \x03(\x0b\x32#.sigprocpacket.SigProcPacket.RXChan\x12\x14\n\x0csequence_num\x18\x02 \x01(\r\x12\x12\n\nkerneltime\x18\x03 \x01(\x01\x1a\x90\x02\n\x06RXChan\x12\x0e\n\x06rxfreq\x18\x01 \x01(\x01\x12\r\n\x05nrang\x18\x02 \x01(\r\x12\r\n\x05\x66rang\x18\x03 \x01(\r\x12K\n\x0f\x62\x65\x61m_directions\x18\x04 \x03(\x0b\x32\x32.sigprocpacket.SigProcPacket.RXChan.BeamDirections\x1a\x8a\x01\n\x0e\x42\x65\x61mDirections\x12G\n\x05phase\x18\x01 \x03(\x0b\x32\x38.sigprocpacket.SigProcPacket.RXChan.BeamDirections.Phase\x1a/\n\x05Phase\x12\x12\n\nreal_phase\x18\x01 \x01(\x01\x12\x12\n\nimag_phase\x18\x02 \x01(\x01\x62\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS_PHASE = _descriptor.Descriptor(
  name='Phase',
  full_name='sigprocpacket.SigProcPacket.RXChan.BeamDirections.Phase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='real_phase', full_name='sigprocpacket.SigProcPacket.RXChan.BeamDirections.Phase.real_phase', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='imag_phase', full_name='sigprocpacket.SigProcPacket.RXChan.BeamDirections.Phase.imag_phase', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=427,
)

_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS = _descriptor.Descriptor(
  name='BeamDirections',
  full_name='sigprocpacket.SigProcPacket.RXChan.BeamDirections',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phase', full_name='sigprocpacket.SigProcPacket.RXChan.BeamDirections.phase', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS_PHASE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=289,
  serialized_end=427,
)

_SIGPROCPACKET_RXCHAN = _descriptor.Descriptor(
  name='RXChan',
  full_name='sigprocpacket.SigProcPacket.RXChan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rxfreq', full_name='sigprocpacket.SigProcPacket.RXChan.rxfreq', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nrang', full_name='sigprocpacket.SigProcPacket.RXChan.nrang', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='frang', full_name='sigprocpacket.SigProcPacket.RXChan.frang', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beam_directions', full_name='sigprocpacket.SigProcPacket.RXChan.beam_directions', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=155,
  serialized_end=427,
)

_SIGPROCPACKET = _descriptor.Descriptor(
  name='SigProcPacket',
  full_name='sigprocpacket.SigProcPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rxchannel', full_name='sigprocpacket.SigProcPacket.rxchannel', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sequence_num', full_name='sigprocpacket.SigProcPacket.sequence_num', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kerneltime', full_name='sigprocpacket.SigProcPacket.kerneltime', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_SIGPROCPACKET_RXCHAN, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=427,
)

_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS_PHASE.containing_type = _SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS
_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS.fields_by_name['phase'].message_type = _SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS_PHASE
_SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS.containing_type = _SIGPROCPACKET_RXCHAN
_SIGPROCPACKET_RXCHAN.fields_by_name['beam_directions'].message_type = _SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS
_SIGPROCPACKET_RXCHAN.containing_type = _SIGPROCPACKET
_SIGPROCPACKET.fields_by_name['rxchannel'].message_type = _SIGPROCPACKET_RXCHAN
DESCRIPTOR.message_types_by_name['SigProcPacket'] = _SIGPROCPACKET

SigProcPacket = _reflection.GeneratedProtocolMessageType('SigProcPacket', (_message.Message,), dict(

  RXChan = _reflection.GeneratedProtocolMessageType('RXChan', (_message.Message,), dict(

    BeamDirections = _reflection.GeneratedProtocolMessageType('BeamDirections', (_message.Message,), dict(

      Phase = _reflection.GeneratedProtocolMessageType('Phase', (_message.Message,), dict(
        DESCRIPTOR = _SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS_PHASE,
        __module__ = 'sigprocpacket_pb2'
        # @@protoc_insertion_point(class_scope:sigprocpacket.SigProcPacket.RXChan.BeamDirections.Phase)
        ))
      ,
      DESCRIPTOR = _SIGPROCPACKET_RXCHAN_BEAMDIRECTIONS,
      __module__ = 'sigprocpacket_pb2'
      # @@protoc_insertion_point(class_scope:sigprocpacket.SigProcPacket.RXChan.BeamDirections)
      ))
    ,
    DESCRIPTOR = _SIGPROCPACKET_RXCHAN,
    __module__ = 'sigprocpacket_pb2'
    # @@protoc_insertion_point(class_scope:sigprocpacket.SigProcPacket.RXChan)
    ))
  ,
  DESCRIPTOR = _SIGPROCPACKET,
  __module__ = 'sigprocpacket_pb2'
  # @@protoc_insertion_point(class_scope:sigprocpacket.SigProcPacket)
  ))
_sym_db.RegisterMessage(SigProcPacket)
_sym_db.RegisterMessage(SigProcPacket.RXChan)
_sym_db.RegisterMessage(SigProcPacket.RXChan.BeamDirections)
_sym_db.RegisterMessage(SigProcPacket.RXChan.BeamDirections.Phase)


# @@protoc_insertion_point(module_scope)
